os: osx
addons:
  homebrew:
    packages:
      - zola
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
jobs:
  include:
    - # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = publication
      script: ./build.sh
