# The URL the site will be built for
base_url = "https://oteku.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Used in RSS by default
title = "Oteku"
description = "Je m'appelle Thomas Haesslé, j'écris quelques essais dans ce carnet sur #ReasonML #OCaml #Rust"

# The default language, used in RSS
default_language = "fr"

# Which theme to use for the code highlighting.
# See below for list of accepted values
highlight_theme = "ayu-mirage"
theme = "docusaurus"
# Whether to generate a RSS feed automatically
generate_rss = true

taxonomies = [
       {name = "tags", rss = true} # each tag will have its own RSS feed
]


[extra]
# Put all your custom variables here
repo_website = {url = "https://github.com/oteku/oteku.github.io", name="Github"}
tags = ["Rust", "ReasonML", "OCaml", "Tooling"]
social = [
    {url = "https://twitter.com/oteku", name = "Twitter", icon = "icon-twitter"},
    {url = "https://mastodon.social/@oteku", name = "Mastodon"},
]
community = [
    {url = "https://www.meetup.com/fr-FR/LambdaLille/", name = "Lambda Lille", icon = "icon-beer"},
    {url = "https://reactbeerlille.org/", name = "React Beer Lille", icon = "icon-beer"},
]
hack = [
    {url = "rss.xml", name = "Flux rss", icon = "icon-rss"},
]
github="https://github.com/oteku"